### ISSUE TITLE
1.2 - Final adjustments

### ISSUE THREAD

**Issue by retailcoder** [retailcoder/Rubberduck#244]
- [x] Test-run every feature
- [x] Add checkboxes to this list.
- [x] Build Release for Testing
- [x] Test every feature again. 
- [x] Write Release Notes

**Comment by retailcoder** [comment]
`IdentifierUsageInspector` must be refactored/optimized into a singleton or something - it's doing too much unnecessary/redundant work.

**Comment by retailcoder** [comment]
Performance issue is solved... but there are LOTS of false positives, and a few more bugs that need to be addressed before releasing.

**Comment by ckuhn203** [comment]
@retailcoder I drafted the [1.2 release notes ][rn]. Feel free to tweak. It's a bit underwhelming considering all of the work you put into the parser and code inspections. I'm not sure how to spruce it up.

[rn]:https://github.com/retailcoder/Rubberduck/releases/tag/untagged-8a3914d56f1da4591a73

**Comment by ckuhn203** [comment]
Feature Tests
 - [x] Unit Testing
 - [ ] Code Explorere
 - [ ] Task List
 - [ ] Extract Method
 - [ ] Settings/Config

**Comment by ckuhn203** [comment]
I'm not sure Extract Method is ready to ship. It doesn't insert the call, but it also removes some code from the highlighted area. Also, the code looks messy compared to the preview. Will open an issue later. We should try to address some of this for 1.2.

**Comment by retailcoder** [comment]
@ckuhn203  still the case now?

**Comment by ckuhn203** [comment]
No. We're ready to ship as soon as I build the installer and do one last test run.
