### ISSUE TITLE
What to do in the next sprint?

### ISSUE THREAD

**Issue by ckuhn203** [retailcoder/Rubberduck#265]
I just went through all of the issues and added ones without miles stones and ones attached to closed milestones to Future Versions. With v1.2 coming soon, it seems like a good time to stop, reflect, and talk about the next sprint. 

The first question I think we need to ask ourselves is,  "What is the goal of the next sprint?" Are we aiming for v1.3 with some new features, or are we going to do some house cleaning? After we decide that, I think we'll be in a better place to decide what actual issues are going to be addressed in the next version. 

Personally I think we might want to consider putting some effort into adding tests, refactoring, and perhaps some of the more minor issues before moving onto v1.3. Thoughts @retailcoder?

**Comment by retailcoder** [comment]
I wouldn't want to release 1.3 without any new features, even if the entire code base gets refactored to death and the whole thing ends up completely rewritten - I agree, we have some cleaning up to do, and we need a truckload more unit tests... but releasing something that's just *under the hood* isn't ideal IMO. Perhaps start with a cleanup and release a v1.25 if the cleanup translates into better performance and overall UX?

I wanted 1.2 to mainly hint at refactoring and expand on code inspections - I'd like 1.3 to be released with integrated source control and expand on refactorings (and to include inspections we couldn't fit into 1.2).

**Comment by ckuhn203** [comment]
Okay. I'd say we're on the same page then. I wouldn't want to release 1.3 without new features either. I think a 1.2.1 is in order. So, yes, under the hood improvements should be made, but with an eye on performance & UX as well. I'm on board with this. (Even though I'm dying to hack out the source control integration).

**Comment by retailcoder** [comment]
@ckuhn203 neither of us can wait for source control integration - v1.3 isn't shipping without it. I'd like 1.3 to introduce more refactorings:

 - [x] GitHub integrated source control
 - [ ] Refactor / inline method
 - [ ] Refactor / promote local
 - [ ] Refactor / extract class
 - [ ] Refactor / extract interface

Also we'll need to find a way to reinstate the disabled inspections:
- [ ] VariableNotDeclaredInspection - that's a tough one; may be impossible with out current grammar.
- [ ] UnassignedVariableUsageInspection - tough on performance.

Some other refactorings are more complex and can go to 1.4
 - [ ] Refactor / rename (variable/member/module/project)
 - [ ] Refactor / reorder parameters
 - [ ] Refactor / remove parameter & update usages
 - [ ] Refactor / safe delete

**Comment by ckuhn203** [comment]
:bump:

**Comment by retailcoder** [comment]
No way *rename* isn't shipping in 1.3!

**Comment by retailcoder** [comment]
With the way identifier usages are now accessible, *safe delete* is looking more and more like the next refactoring that should be implemented. Parameter/signature-related ones would come after that, but we'll need a better way of handling the parameter/method relationship.

So for 1.3 to ship around 04/18 I think I'll focus on navigation and get *find all references* done, and polish the *rename* refactoring a bit, pushing *extract method* cleanup & enhancements to 1.4 but if source control is ready by then we'll just drop 1.4 and go with 2.0 right away... so I think after the *extract method* refactoring is switched to use the `Declarations` API I'll start getting serious about localization and work on UI issues.
